### ISSUE TITLE
Black Screen after Install

### ISSUE THREAD

**Issue by SonicGerkor** [foolishmortalbuilders/magicbandreader#9]
### Black Screen after running install.sh

So, I have a 2gb micro SD for this, and I don't really know if after installing it ends up being a lot bigger in size.
I finished with the `sudo sh install.sh` correctly, and after rebooting, the screen never turned on again.
I tried everything and I can't even access recovery mode.

Any thoughs?
Thanks!

**Comment by scottoliver** [comment]
Guessing the card might be full. I just installed on an 8GB card and 1.8 GB are being used before editing settings.conf, adding sound files, etc.

**Comment by SonicGerkor** [comment]
It was memory error
